name: Playwright Tests (Sharded + Allure)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4] # количество шардов

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npm ci

      - run: npx playwright install --with-deps

      - name: Run Playwright shard
        run: npx playwright test --shard=${{ matrix.shard }}/4

      # сохраняем allure results каждого шарда
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.shard }}
          path: allure-results

  merge-reports:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      # скачать все артефакты
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      # объединяем все allure-results
      - name: Merge Allure Results
        run: |
          mkdir merged-results
          find artifacts -type f -name "*.json" -exec cp {} merged-results \;

      - name: Generate Allure Report
        run: allure generate merged-results --clean -o allure-report

      - uses: actions/upload-artifact@v4
        with:
          name: final-allure-report
          path: allure-report

  deploy:
    needs: merge-reports
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Download final report
        uses: actions/download-artifact@v4
        with:
          name: final-allure-report
          path: allure-report

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4